name: FireScrape

channels:
  - conda-forge
  
dependencies:
  - python=3.7
  - pip
  - pandas
  - matplotlib
  - jupyterlab
  - seaborn
  - yaml
  - fire
  
  - pip:
      - -e .
      - gitpython
      - ipypb
      - feautils
